applications/DG-Max/DGMaxProgramUtils.cpp, applications/DG-Max/DGMaxProgramUtils.h, applications/DG-Max/Programs/DGMaxEigen.cpp
The path specification could be used in multiple programs (e.g. a
plotter for theoretical band diagrams). It should therefore not reside
in DGMaxEigen.
=> Separate parsing of a path

kernel/Utilities/GlobalIndexing.cpp, kernel/Utilities/GlobalIndexing.h
To allow use in a more general context these functions have been made
const. No implementation changes were needed.
=> Make GlobalIndexing functions const where possible

kernel/Utilities/GlobalIndexing.cpp
The last element of the list is at index n when there are n-entries for the procesors and an extra one at the start.
Fixes #10
=> Fix an off-by-one issue in GlobalIndexing

kernel/Base/Element.h, tests/self/Basic/070ChangeOfBasisFunctions_SelfTest.cpp
When using a scheme with multiple unknowns where at least one has a different type of basis function, calling `use***BasisFunctions(order)`, the one without the unknown-parameter, would crash. The cause was that the basis functions would be deleted at the start of the method, when setting the basis function on each element through `setDefaultBasisFunctionSet(position, unknown)` it would do so unknown by unknown. When setting the first unknown only the information of the first unknown would be cleared, the out-dated information for the other unknowns would remain. As the code for setting the basis function also updates the quadrature rules, it tried to determine the maximum order of these old basis functions. As these were already deleted the code did crash.
The fix here is to start by …
=> Fix changing basis functions for mixed formulation

applications/DG-Max/Algorithms/DGMaxEigenValue.cpp, applications/DG-Max/Algorithms/DivDGMaxEigenValue.cpp, applications/DG-Max/Programs/DGMaxEigen.cpp, applications/DG-Max/Utils/KSpacePath.cpp
Update DGMaxEigen to allow using both the DGMax and DivDGMax discretization using the --method flag.
Additionally, the difference that DivDGMax did not compute the eigenvalues of the first k-point and DGMax did, has been removed by letting them both compute the eigenvalues at the first point.
=> Dgmax in dgmaxeigen

kernel/Base/CMakeLists.txt, kernel/Base/Edge.cpp, kernel/Base/Edge.h, kernel/Base/Face.h, kernel/Utilities/GlobalMatrix.cpp, kernel/Utilities/SparsityEstimator.cpp, kernel/Utilities/SparsityEstimator.h, tests/self/PETSc/007SparsityEstimator_SelfTest.cpp
This replaces the code to estimate the number of non zero entries for `GlobalMatrix` by a new class `SparsityEstimator` that should exactly compute the sparsity pattern. Unlike the previous code this is tested and documented.
In addition to the included unit test it is also tested by setting the `MAT_NEW_NONZERO_ALLOCATION_ERR` option on the PetscMatrix, which causes errors when new entries need to be allocated. With this option set both the test suite and DGMax have been run.
=> Improved matrix entry estimate code

CMakeLists.txt, kernel/LinearAlgebra/MiddleSizeMatrix.cpp, kernel/LinearAlgebra/MiddleSizeMatrix.h, kernel/LinearAlgebra/MiddleSizeVector.cpp, kernel/LinearAlgebra/MiddleSizeVector.h
According to the doc it is broken and it has not been used and there is no benefit in keeping both, especially with modern compilers. 
If we want a better linear algebra package, we can still apply Eigen or some other linear algebra package.
=> removed val_array

kernel/Base/Mesh_Impl.h
These warnings cluttered the output, without really giving an advantage.
=> Remove verbose warnings from Mesh_Impl

kernel/Base/LevelTree.h, kernel/Base/MeshManipulator_Impl.h
Some simple fixes to make the mesh refinement function compile again. This was broken by the introduction of explicit ownership in b4d28c9 (and some later commits), but the compiler did not detect it.
=> Refinement fixes

.github/workflows/Basic.yml, .github/workflows/PETSC_complex.yml, .github/workflows/QHull.yml, .github/workflows/checkformat.yml, .github/workflows/codecov.yml, .github/workflows/macos.yml
As the job names for the github workflows were identical, there was no
way to distinguish them when the workflow name was not included. This is
for example a problem when protecting branches, where only the jobids
are listed.
=> Rename all job ids for the workflows

kernel/Utilities/BasisFunctions1DH1ConformingLine.cpp, kernel/Utilities/BasisFunctions1DH1ConformingLine.h, kernel/Utilities/BasisFunctions2DH1ConformingTriangle.cpp, kernel/Utilities/BasisFunctions2DH1ConformingTriangle.h, kernel/Utilities/BasisFunctions2DNedelec.cpp, kernel/Utilities/BasisFunctions2DNedelec.h, kernel/Utilities/BasisFunctionsPiecewiseConstant.cpp, kernel/Utilities/BasisFunctionsPiecewiseConstant.h, tests/unit/Utilities/020Nedelect2D_UnitTest.cpp
This replaces the implementation Nédélec basis functions on a triangle so that we can support more than just the lowest order.
These basis functions are used in DGMax, and we currently only support higher order Nédélec functions on tetrahedra. Adding higher order ones in 2D means that we can test codes with higher order basis functions in 2D instead of 3D. This is much cheaper from a computational point of view.
=> Higher order 2dnedelec

applications/DG-Max/Algorithms/DivDGMaxEigenvalue.cpp, applications/DG-Max/Algorithms/DivDGMaxEigenvalue.h, applications/DG-Max/Utils/CGDGMatrixKPhaseShiftBuilder.cpp, applications/DG-Max/Utils/FaceKPhaseShiftBuilder.cpp, applications/DG-Max/Utils/KPhaseShiftHelpers.h
Replace the manual phase shifts in `DivDGMaxEigenvalue` with the abstracted approach from `KPhaseShift`.
As can be seen in the diff, this removes a lot of complicated index-fiddling in DivDGMaxEigenvalue.
=> Kshift divdgmax eigenvalue

applications/DG-Max/Algorithms/DivDGMaxEigenvalue.cpp, applications/DG-Max/Algorithms/DivDGMaxEigenvalue.h
It was not used and is not expected to give any significant advantage at the moment.
=> Remove between k-point shift from DivDGMaxEigenvalue

applications/DG-Max/Utils/KPhaseShift.cpp, applications/DG-Max/Utils/KPhaseShift.h
Because we did not keep track of the previous k-value the shifting was incorrect. This removes it entirely, as it only gives a minor improvement.
=> Fix the KPhase shifting

kernel/Utilities/GlobalVector.cpp
Taking a global vector and writing it as local vector (time integration one) did take the real part of the coefficients. This is strange, as
this discards any imaginary part of the solution. This is especially problematic when plotting the solution or locally computing an error, as there the imaginary part will have been discarded.
Search through the history I could not find a reason for taking the real part (though I did remove it unintentionally and undid that at r925-926).
=> Remove Global->Local Vector taking real part

applications/DG-Max/Algorithms/DGMaxEigenvalue.cpp, applications/DG-Max/Algorithms/DGMaxEigenvalue.h
Similar to a change done in #75, this updates `DGMaxEigenvalue` to also use inner classes for its implementation details (similar to `DivDGMaxEigenvalue` in #75). This should prevent accidental name clashes in the future.
Note:
- This is mainly a mechanical update, no details were considered (nor changed)
- The structure of DGMaxEigenvalue and DivDGMaxEigenvalue is very similar. Removing this duplication would be nice, but both algorithms are currently in such a state of flux that I don't think it is advisable to do so now.
=> DGMaxEigenvalue workspace inner class update

.github/workflows/Basic.yml, .github/workflows/PETSC_complex.yml, .github/workflows/macos.yml
This to make debugging the result considerably easier, as the current output only shows that a test has failed, but not why.
=> Print verbose output on workflow ctest failure

conf/cmake/Modules/FindPETSc.cmake, conf/cmake/Modules/FindSLEPc.cmake
Without it the find modules will fail anyway, this is just making it fail faster and with a clearer message.
=> Mark finding PETSc/SLEPc required

applications/Preprocessor/centaur.cpp, applications/Preprocessor/centaur.h
Basic fixes for reading 2D centaur meshes. Which I apparently did not sufficiently test enough.
Reading of boundary information is at the moment useless (and discarded), but it provided good insight into whether the reading process was good or not. As it is far easier to check if a name makes sense, than some seemingly random numbers. 
Because there may be use for this boundary information, either for future debugging, or actually in the preprocessor, I have left the reading code in.
=> Centaur reader fixes

applications/DG-Max/Programs/DGMaxEigen.cpp
Pretty self explanatory. The original use for #80, now the code to actually use it in practice.
=> Use higher order output for DGMaxEigen

applications/DG-Max/Programs/DGMaxEigen.cpp
Format the output of DGMaxEigen so that the columns mat MPB output as much as close as possible.
=> Align DGMaxEigen output with MPB output

applications/Preprocessor/centaur.cpp, applications/Preprocessor/centaur.h, applications/Preprocessor/customIterator.h, applications/Preprocessor/customVector.h, applications/Preprocessor/elementShape.h, applications/Preprocessor/elementShape_impl.h, applications/Preprocessor/hpgem.cpp, applications/Preprocessor/hpgem.h, applications/Preprocessor/main.cpp, applications/Preprocessor/mesh.h, applications/Preprocessor/meshData.h, applications/Preprocessor/mesh_impl.h, applications/Preprocessor/output.h, applications/Preprocessor/output_impl.h, applications/Preprocessor/unstructuredFile.h
This moves the `using namespace hpgem` into the Preprocessor namespace
scope. For that it was required to introduce this namespace explicitly
in some of the cpp files.
Additionally, some unused include statements were removed.
=> Cleanup namespaces and includes in the Preprocessor

kernel/Base/Edge.cpp, kernel/Base/Face.cpp, kernel/Base/Face.h, kernel/Base/Node.cpp
Work from an old branch. Each face, edge and node has an owner. If we own the part then we are certain about the owner, but for parts in the ghost layer we may have insufficient data to determine the owner with certainty. To prevent accidents from reporting the wrong owner, a rather conservative check was added to each of the parts. That is, a fail safe design was used, better report that it is not possible to determine the owner than report the wrong one.
Improved knowledge about the mesh, and ghost layer specifically, allowed widening the number of cases where we could determine the owner of a part with certainty.
=> Expand the correctly calculated owningElements

applications/Preprocessor/lib/hpgem.cpp, applications/Preprocessor/lib/mesh.h, applications/Preprocessor/lib/mesh_impl.h
Fixes to problems found when trying to use #103 and #109 together to use the new mesh format.
Fixes:
- The zone was passed from the MeshSource to addElement(), but the latter did not actually use it.
- The elements generated by the structured mesh generator did not have any zone information.
As backup to the second problem a check is placed that checks if an actual zone is present.
=> Fix zone assignment in preprocessor

kernel/Base/Element.h, kernel/Geometry/ElementGeometry.cpp, kernel/Geometry/ElementGeometry.h, kernel/Geometry/Mappings/MappingReferenceToPhysical.h, kernel/Geometry/Mappings/MappingToPhysHypercubeLinear.cpp, kernel/Geometry/Mappings/MappingToPhysHypercubeLinear.h, kernel/Geometry/Mappings/MappingToPhysPyramid.cpp, kernel/Geometry/Mappings/MappingToPhysPyramid.h, kernel/Geometry/Mappings/MappingToPhysSimplexLinear.h, kernel/Geometry/Mappings/MappingToPhysSimplexLinear_Impl.h, kernel/Geometry/Mappings/MappingToPhysTriangularPrism.cpp, kernel/Geometry/Mappings/MappingToPhysTriangularPrism.h, tests/unit/Geometry/220ElementGeometry_UnitTest.cpp, tests/unit/Geometry/Mappings/010MappingToPhysicalHypercubeLinear_UnitTest.cpp, tests/unit/Geometry/Mappings/020MappingToPhysicalSimplexLinear_UnitTest.cpp, tests/unit/Geometry/Mappings/030MappingToPhysicalTriangularPrism_UnitTest.cpp, tests/unit/Geometry/Mappings/040MappingToPhysicalPyramid_UnitTest.cpp
This changes the mapping between Reference and Physical space. That is, the transformations used to convert between the elements in the mesh (triangles, tetrahedra, etc.) and their reference counter parts which are used to define the basis functions.
This PR replaces the old interface that was a specialization of `MappingInterface<0>` that had methods for dimensions 1-4. It is replaced by a version that is templated on the dimension argument plus a base class without the dimension argument. This is in my view a much cleaner and flexible way to define these mappings, as it does only have the methods for the right dimension.
Reviewing advice:
1. Look at #121, this code uses the new class introduced there
2. Look at `MappingReferenceToPhysical`
3. The rest is refactoring to match the new …
=> Fixed dimension ReferenceToPhysicalMapping (uses #121)

kernel/Utilities/GlobalMatrix.cpp, kernel/Utilities/GlobalMatrix.h
I often have to duplicate the code exporting the raw Petsc `Mat` object.  This PR exposes the code that exposes these matrices so that I don't have to keep on duplicating it.
=> Add export for non managed matrices

applications/DG-Wave_linear/main.cpp, kernel/Base/Element.h, kernel/Base/MeshManipulator.h, kernel/Base/MeshManipulator_Impl.h, tests/unit/Base/BasisFunctionChange_UnitTest.cpp
The basis function count was not reset correctly when switching between different basis functions. 
When changing from CG to DG basis functions on the same mesh (probably does not happen in practice), the number of basis functions on Nodes, Edges and Faces was incorrect.
=> Reset basis function count

applications/DG-Max/Algorithms/DGMaxDiscretization.cpp, applications/DG-Max/Algorithms/DGMaxDiscretization.h, applications/DG-Max/Algorithms/DGMaxHarmonic.cpp, applications/DG-Max/Algorithms/DGMaxTimeIntegration.cpp, applications/DG-Max/Algorithms/DivDGMaxDiscretization.cpp, applications/DG-Max/Algorithms/DivDGMaxDiscretization.h, applications/DG-Max/Algorithms/DivDGMaxHarmonic.cpp, applications/DG-Max/ProblemTypes/Harmonic/SampleHarmonicProblems.cpp, applications/DG-Max/ProblemTypes/Harmonic/SampleHarmonicProblems.h, applications/DG-Max/ProblemTypes/HarmonicProblem.h, applications/DG-Max/ProblemTypes/Time/DummyTestProblem.cpp, applications/DG-Max/ProblemTypes/Time/DummyTestProblem.h, applications/DG-Max/ProblemTypes/Time/SampleTestProblems.cpp, applications/DG-Max/ProblemTypes/Time/SampleTestProblems.h, applications/DG-Max/ProblemTypes/TimeIntegrationProblem.h
The problem definitions for DGMax define many functions that go into the
PDE, for example boundary values and source terms. These functions are
refactored here to be more readable. In particular the follow changes
have been made:
- Replaced returning the results by reference to just by value, thus:
refactoring  void f(...., Vector<DIM>& result) to Vector<DIM> f(....)
- Removed passing both a PointPhysical and a PhysicalFace. The latter
contains the current point of evaluation, removing the need for the
former.
The rest of the refactoring is just adjusting the code to work with the new signatures. The only cleanup considered was removing now unused variables.
Note #138 introduces a new source problem, so depending on merge order one of them needs to be adjusted.
=> Refactor Problems in DGMax

applications/DG-Max/Algorithms/DGMaxDiscretization.cpp, applications/DG-Max/Algorithms/DGMaxDiscretization.h, applications/DG-Max/Algorithms/DGMaxEigenvalue.cpp, applications/DG-Max/Algorithms/DGMaxHarmonic.cpp, applications/DG-Max/Algorithms/DGMaxHarmonic.h, applications/DG-Max/Algorithms/DGMaxTimeIntegration.cpp, applications/DG-Max/Algorithms/DGMaxTimeIntegration.h, kernel/Base/FaceData.cpp, kernel/Base/FaceData.h, kernel/Base/FaceMatrix.cpp, kernel/Base/FaceMatrix.h
The primary step of this refactoring is to take the complicated matrix assembly step and restructure it. The original  implementation had a loop over the elements/faces that did several things:
- Run the integrator
- Delegate the integrand to a function
- Postprocess the resulting matrix/matrices for the mass matrix
- Store the matrices as element/face matrix
- [not modified] Compute element/face vectors
This refactoring unclutters this process to only two function calls:
1. Call a function to compute the face/element matrices
2. Call a function to post process the matrices
The first function does the integration for each type of matrix and stores them in the element/face. The second one takes the matrix and the and post processes them as required. I decided to keep them in this fashion, …
=> Refactor DGMaxDiscretization matrix construction

applications/DG-Max/Algorithms/DivDGMaxDiscretization.cpp, applications/DG-Max/Algorithms/DivDGMaxDiscretization.h
The cause is that the constructor to std::function allows very general types. So general that type checking becomes almost powerless.
Some unit tests for (Div)DGMax will follow separately.
=> Fix the source function in DivDGMax

applications/DG-Max/Algorithms/DivDGMaxDiscretization.cpp, applications/DG-Max/Algorithms/DivDGMaxDiscretization.h, applications/DG-Max/Algorithms/DivDGMaxEigenvalue.cpp, applications/DG-Max/Algorithms/DivDGMaxEigenvalue.h, applications/DG-Max/Algorithms/DivDGMaxHarmonic.cpp, applications/DG-Max/Algorithms/DivDGMaxHarmonic.h, applications/DG-Max/Programs/DGMaxEigen.cpp, applications/DG-Max/Programs/DGMaxEigenConvergence.cpp, applications/DG-Max/Programs/DGMaxSource.cpp, applications/DG-Max/Utils/Verification/DivDGMaxEVConvergenceTest.h, kernel/Base/PhysicalElement.h, kernel/Base/PhysicalElement_Impl.h, kernel/Base/PhysicalFace.h, kernel/Base/PhysicalFace_Impl.h, kernel/Utilities/FaceLocalIndexing.h
I got frustrated with DivDGMaxDiscretization being far from elegant. This PR improves several parts.
The following things have been tackled:
1. Reduce the number of integrators and transforms by sharing one set of them
2. Extract a dimensionless base class for the discretization
3. Move the code creating the element matrices inside a function.
4. Replace the ~5 face integrands by 2, reducing the code duplication
5. Remove excessive caching, this was recaching what was in PhysicalFace.
6. Replace the way how input functions are passed to create element/face vectors
7. Some minor type improvements.
Especially the face integrals of DivDGMaxDiscretization were significantly modified. The diff does not really look legible, split view might improve it, or otherwise look at the resulting …
=> Cleanup divdgmax discretization

.github/workflows/codecov.yml, applications/DG-Max/Algorithms/DGMaxDiscretization.cpp, applications/DG-Max/Algorithms/DGMaxDiscretization.h, applications/DG-Max/Algorithms/DGMaxHarmonic.cpp, applications/DG-Max/Algorithms/DivDGMaxDiscretization.cpp, applications/DG-Max/Algorithms/DivDGMaxDiscretization.h, applications/DG-Max/Algorithms/DivDGMaxHarmonic.cpp, applications/DG-Max/ProblemTypes/BoundaryConditionType.h, applications/DG-Max/ProblemTypes/Harmonic/SampleHarmonicProblems.h, applications/DG-Max/ProblemTypes/HarmonicProblem.h, applications/DG-Max/Programs/DGMaxSource.cpp, kernel/Utilities/GlobalVector.cpp, kernel/Utilities/GlobalVector.h, tests/self/ConvergenceTest.h, tests/self/DGMax/DGMax_PlaneWave_SelfTest.cpp
Adds a different type of boundary condition to (Div)DGMax. The previous code only allowed specifying the transverse part of the electric field (Dirichlet-style boundary condition). This PR changes adds the option to specify the transverse part of the magnatic field (= curl of electric field), which is a Neumann-style boundary condition.
Review recommendation:
First review
- `BoundaryConditionType` giving a description of the boundary conditions
-  `HarmonicProblem` the class that specifies which boundary condition should be used
=> Dgmax boundary conditions2

applications/DG-Max/Algorithms/DivDGMaxDiscretization.h, kernel/FE/BasisFunctionSet.h, kernel/Geometry/ReferenceSimplex.h, kernel/LinearAlgebra/CMakeLists.txt, kernel/LinearAlgebra/MiddleSizeVector.h, kernel/LinearAlgebra/SmallVector.cpp, kernel/LinearAlgebra/SmallVector.h, kernel/LinearAlgebra/Types.h, tests/unit/LinearAlgebra/SmallVectorUnitTest.cpp
Introduces the option to have complex valued vectors of fixed size (`SmallVectorC`).
This is quite a bit more messy than expected due to several complicating factors:
1. There are several differences between `double` and `complex<double>` in the standard library, like '<' working only on doubles, and `std::conj` always returning a `complex<double>`.
2. The specialization of CrossProduct for vectors of size 2 and 3 now becomes a partial specialization
3. The MiddleSizeVector (and matrix for that matter), can be real or complex valued depending on what petsc uses, which makes conversion SmallVector <-> MiddleSizeVector complicated. Removing this ambiguity from MiddleSizeVector is very time intensive, as it is intertwined with the Mesh.
This PR tries to balance time investment against doing …
=> Complex smallvector

CMakeLists.txt, conf/cmake/ConfigureDependencies.cmake
The previous configuration globbed all the files, including local
build dependencies
=> Restrict clang format globbing

applications/DG-Max/Algorithms/DGMaxDiscretization.cpp, applications/DG-Max/Utils/CGDGMatrixKPhaseShiftBuilder.cpp, applications/DG-Max/Utils/FaceKPhaseShiftBuilder.cpp, applications/DG-Max/Utils/KPhaseShiftHelpers.h
Fixes to get DGMaxDiscretization to work with MPI meshes. Partially undoing overzealos fix in #173.
=> Dgmax face integrals mpi fix

applications/Preprocessor/lib/FortranUnformattedFile.cpp, conf/cmake/ConfigureDependencies.cmake, kernel/Geometry/ElementGeometry.h, kernel/Geometry/Mappings/MappingRefLineToTetrahedron.cpp, kernel/Geometry/Mappings/MappingRefLineToTetrahedron.h, kernel/Geometry/Mappings/MappingToPhysTetrahedronQuadratic.h
A typo accidentally meant that the formatting always crashed without
doing anything.
=> Fix the configuration of the formatter

applications/DG-Max/DGMaxProgramUtils.cpp, applications/DG-Max/DGMaxProgramUtils.h, applications/DG-Max/Programs/DGMaxEigen.cpp, applications/DG-Max/Programs/DGMaxSource.cpp
The written mesh by DGMaxEigen was using a linear mesh, irrespective of whether the mesh used curvilinear elements. This commit changes it to determine the geometric order of the mesh and use that to output the mesh sample.
=> Output higher order mesh input in DGMaxEigen

.github/workflows/checkformat.yml, applications/DG-Max/ProblemTypes/Harmonic/SampleHarmonicProblems.h, conf/cmake/ConfigureDependencies.cmake, conf/cmake/Modules/FindCLANG_FORMAT.cmake, kernel/AbstractDimensionlessBase.h
Switch from clang format 10 to 11.1. The version 10 is no longer available as mac brew, and also not available on the newer ubuntu CI vms.
=> Clang format 11

applications/Preprocessor/lib/gmsh.cpp, applications/Preprocessor/lib/gmsh.h, tests/unit/Preprocessor/001gmsh_UnitTest.cpp
The gmsh reader incorrectly interpreted the number of periodic entities number. As result it did not correctly read the case with >1 periodic entities.
This commit fixes this issue, and migrates the handling of periodic entities to the new style. That is, specify the periodic connections rather than directly merging node coordinates.
=> Fix gmsh reading of multiple periodic boundaries

tests/self/DGMax/DGmax_Vacuum2D_SelfTest.cpp, tests/self/DGMax/DivDGmax_Vacuum2D_SelfTest.cpp
The boolean flags can only be set to true (limit from our command line parser). So switch it from default true, to default false. Also updates documentation from DGMaxVacuum self test which uses the same logic.
=> Fix the flag for DivDGmaxVacuum self test

applications/Preprocessor/lib/centaur.cpp
For example the version 4 meshes that are part of the tests. These don't have the additional internal data that the reader tried to read.
=> Fix reading <6.5 centaur meshes

.github/workflows/PETSC_complex.yml, .github/workflows/codecov.yml, applications/DG-Max/Programs/DGMaxEigen.cpp
Print both kmag and eigenfrequencies in full precision. This is needed with very accurate convergence tests. Note, kx, ky, kz are not printed in full precision as these are input (or interpolated).
=> Print full precision in DGMaxEigen

applications/DG-Max/Utils/CGDGMatrixKPhaseShiftBuilder.cpp
They were added in the loop, such that each edge/node was added on multiple times instead of only once.
Cherry-pick: Needed to add the indexing
--
Old fix that did not get into master
=> Fix KPhaseShift adding edges/nodes

kernel/Base/MeshManipulator_Impl.h, kernel/Base/Node.cpp, kernel/Base/Node.h, kernel/Geometry/ReferenceCurvilinearElement.h, kernel/Geometry/ReferenceGeometry.h, tests/self/Basic/010HigherOrderElementsOnCurvilinear.cpp
Fix that the all the nodes of curvilinear elements would get conforming basis functions. The geometrical nodes (those purely for the shape) should not get basis functions, and are excluded by this PR.
=> Fix curvilinear node basis functions

applications/DG-Max/Programs/DGMaxEigen.cpp, applications/DG-Max/Utils/PredefinedStructure.cpp, applications/DG-Max/Utils/PredefinedStructure.h
Primarily useful when using homogeneous medium, braggstack or square hole, where a structured mesh can be used.
=> Add option for epsilon of predefined structures
